1.0.0.9_A
Mesabrook-Development-Team/Immersibrook pull request #62
Opened 2023-07-20 21:26 UTC by RavenholmZombie

2023-07-20 21:30 UTC, CSX8600 requested changes
Looks like that Reference change did not stick somehow

2023-07-20 21:30 UTC, RavenholmZombie commented on src/main/java/com/mesabrook/ib/util/Reference.java
> +	public static final int MAX_PHONE_BACKGROUNDS = 42; // This is an INCLUSIVE number
fuck

2023-07-20 21:35 UTC, RavenholmZombie commented on src/main/java/com/mesabrook/ib/util/Reference.java
> +	public static final int MAX_PHONE_BACKGROUNDS = 42; // This is an INCLUSIVE number
Fixed in https://github.com/Mesabrook-Development-Team/Immersibrook/commit/b32dcc8cefe867a2cf59924b4f2805be61bcfb1d

2023-07-21 01:44 UTC, CSX8600 approved these changes

2023-07-21 01:55 UTC, merged